server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/skillsync_auth
    username: root
    password: Security@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: axaxgagfcagaxugjacahcxacxiahcxjahcxahcxajhacjhajaa
  expiration: 86400000 # 1 day
