server:
  port: 8085

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/skillsync_chat
    username: root
    password: Security@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
